language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
cache:
  directories:
    - .gmsh
install:
  - sudo apt-get update
  - sudo apt-get install gmsh libsuitesparse-dev
  - cd .gmsh
  - wget -nc http://gmsh.info/bin/Linux/gmsh-4.5.2-Linux64.tgz
  - tar zvxf gmsh-4.5.2-Linux64.tgz
  - sudo cp gmsh-4.5.2-Linux64/bin/gmsh /usr/bin
  - cd ..
  - wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda create -q -n scikit-fem python=$TRAVIS_PYTHON_VERSION nomkl numpy scipy matplotlib ipython pip
  - source activate scikit-fem
  - pip install meshio dmsh scikit-sparse pacopy pygmsh pyamg
script:
  - python -m unittest discover

jobs:
  include:
    - stage: deploy
      script: skip
      python: 3.7
      deploy:
        provider: pypi
        user: knl
        password:
          secure: "Po/ELXw2W5xxYx08F3cbyFqeQaTEMCczpGdi6N2UNxaZcFAjU7qAcjrwu9Wo1J7qRE1ZdDnEyVIlDK8eIn4vVRFevaGHlzaIMSYWWTP3goA8eKK2DC8POAQptXhWnZEev9oQoDBURIPnw1+lqzgZjdEpNKuR39S/ZUvhY4jugUSDDIvvmR1oMAEs0dUTwoqKW/bnRYd1biNh58GloIffEZHqLD5wKMnDuyb02nrAjzjga2Wr7HbiiDH09+8AUPm9wO53Z/DdGUM+8n8J4m0mQAIjYiLmkviOf2LfJGniDYbVdMc2d92UFmxq5iFzfDmGe4gW+vFUWdQPhRQ6+lrTxul0G+RZD9CQ8Kgu8EK/zGEQ9kJ3/otP4+kvm2wHh/puaLquX5m5bKNNyPf/3SCv1Fn16ZSofNdGK0zsHpoR1tfm2EoY8YzXSdJASA3GHfRhllmbbd6oePkAvPM2qAsFDWzKj4oeQuH/MQmhfJGOE22Dp0/upY+ySXUYJR3bSRKcEmclYWzbZggnLrjoiOUlyAG01oQf9cake2IO6X+F1nO+1AhdafXoxm+xArWuX+02NBnmErH1rKIR5ol2Xf2+XcghWuEUkbRGkKqSjFIT/4qhToji9qpaRHXIVxPxXJ5v2ABodK2m2+DDO6wNSsNRzWDa1UuDsY4ZAuFK6+f8ze8="
        on:
          tags: true
          branch: master
